### ISSUE TITLE
Travis config appears to be wrong

### ISSUE THREAD

**Issue by pfmoore** [pypa/sampleproject#54]
The suggested Travis config fails when testing Python 3.x. As far as I can see, it runs all 3 tests under Python 2.7, even though the ```TOXENV``` variable is set to 3.x.

I don't know much about configuring Travis, but the following (stolen from pip) seems to work better:

```
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
```

Is that the right approach?
